// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ErrorDetailItem defines model for ErrorDetailItem.
type ErrorDetailItem struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

// ErrorResponse エラー時のレスポンス本文（README の形式に準拠）
type ErrorResponse struct {
	// Details フィールド単位のエラー（任意）
	Details *[]ErrorDetailItem `json:"details,omitempty"`

	// Error エラーメッセージ（概要）
	Error string `json:"error"`

	// Type エラー種別
	Type string `json:"type"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	// Token トークン
	Token string `json:"token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email openapi_types.Email `json:"email"`

	// Name ユーザ名（README の「整数」は誤記とみなし string とした）
	Name     string `json:"name"`
	Password string `json:"password"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// Id ユーザID
	Id uint64 `json:"id"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody = LoginRequest

// PostV1AuthRegisterJSONRequestBody defines body for PostV1AuthRegister for application/json ContentType.
type PostV1AuthRegisterJSONRequestBody = RegisterRequest
